// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (owner_id, name, currency, is_system)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, name, balance, currency, is_system, created_at
`

type CreateAccountParams struct {
	OwnerID  pgtype.UUID
	Name     string
	Currency string
	IsSystem bool
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.OwnerID,
		arg.Name,
		arg.Currency,
		arg.IsSystem,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Balance,
		&i.Currency,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, owner_id, name, balance, currency, is_system, created_at FROM accounts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Balance,
		&i.Currency,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, owner_id, name, balance, currency, is_system, created_at FROM accounts
WHERE id = $1
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetAccountForUpdate(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Balance,
		&i.Currency,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getSettlementAccount = `-- name: GetSettlementAccount :one
SELECT id, owner_id, name, balance, currency, is_system, created_at FROM accounts
WHERE is_system = TRUE AND name = 'Settlement Account'
LIMIT 1
`

func (q *Queries) GetSettlementAccount(ctx context.Context) (Account, error) {
	row := q.db.QueryRow(ctx, getSettlementAccount)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Balance,
		&i.Currency,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const getSettlementAccountForUpdate = `-- name: GetSettlementAccountForUpdate :one
SELECT id, owner_id, name, balance, currency, is_system, created_at FROM accounts
WHERE is_system = TRUE AND name = 'Settlement Account'
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetSettlementAccountForUpdate(ctx context.Context) (Account, error) {
	row := q.db.QueryRow(ctx, getSettlementAccountForUpdate)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Balance,
		&i.Currency,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const listAccountsByOwner = `-- name: ListAccountsByOwner :many

SELECT id, owner_id, name, balance, currency, is_system, created_at FROM accounts
WHERE owner_id = $1
ORDER BY created_at DESC
`

// locks row for update, prevents TOCTOU races
func (q *Queries) ListAccountsByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Balance,
			&i.Currency,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE accounts
SET balance = balance + $1
WHERE id = $2
`

type UpdateAccountBalanceParams struct {
	Balance pgtype.Numeric
	ID      pgtype.UUID
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, arg.Balance, arg.ID)
	return err
}
