// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (account_id, debit, credit, transaction_id, operation_type, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, account_id, debit, credit, transaction_id, operation_type, description, created_at
`

type CreateEntryParams struct {
	AccountID     pgtype.UUID
	Debit         pgtype.Numeric
	Credit        pgtype.Numeric
	TransactionID pgtype.UUID
	OperationType OperationType
	Description   pgtype.Text
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.AccountID,
		arg.Debit,
		arg.Credit,
		arg.TransactionID,
		arg.OperationType,
		arg.Description,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Debit,
		&i.Credit,
		&i.TransactionID,
		&i.OperationType,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT CAST((COALESCE(SUM(credit), 0::NUMERIC) - COALESCE(SUM(debit), 0::NUMERIC)) AS NUMERIC(19,4)) AS calculated_balance
FROM entries
WHERE account_id = $1
`

func (q *Queries) GetAccountBalance(ctx context.Context, accountID pgtype.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getAccountBalance, accountID)
	var calculated_balance pgtype.Numeric
	err := row.Scan(&calculated_balance)
	return calculated_balance, err
}

const listEntriesByAccount = `-- name: ListEntriesByAccount :many
SELECT id, account_id, debit, credit, transaction_id, operation_type, description, created_at FROM entries
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEntriesByAccountParams struct {
	AccountID pgtype.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListEntriesByAccount(ctx context.Context, arg ListEntriesByAccountParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntriesByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Debit,
			&i.Credit,
			&i.TransactionID,
			&i.OperationType,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByTransaction = `-- name: ListEntriesByTransaction :many
SELECT id, account_id, debit, credit, transaction_id, operation_type, description, created_at FROM entries
WHERE transaction_id = $1
ORDER BY created_at
`

func (q *Queries) ListEntriesByTransaction(ctx context.Context, transactionID pgtype.UUID) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntriesByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Debit,
			&i.Credit,
			&i.TransactionID,
			&i.OperationType,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
